{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/scipy/scipy/issues/14713",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/scipy/scipy/pull/15013",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "http://www.square16.org/achievement/cve-2023-29824/",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565",
            "tags": [
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T14:14:40.034Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 9.8,
              "attackVector": "NETWORK",
              "baseSeverity": "CRITICAL",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "integrityImpact": "HIGH",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "HIGH"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2023-29824",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-07-22T19:30:04.549547Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:scipy:scipy:-:*:*:*:*:*:*:*"
            ],
            "vendor": "scipy",
            "product": "scipy",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "lessThan": "1.8.0",
                "versionType": "custom"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-416",
                "description": "CWE-416 Use After Free"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-07-22T19:30:57.655Z"
        }
      }
    ],
    "cna": {
      "tags": [
        "disputed"
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "status": "affected",
              "version": "n/a"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/scipy/scipy/issues/14713"
        },
        {
          "url": "https://github.com/scipy/scipy/pull/15013"
        },
        {
          "url": "http://www.square16.org/achievement/cve-2023-29824/"
        },
        {
          "url": "https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "text",
              "description": "n/a"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2023-07-11T00:00:00"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2023-29824",
    "state": "PUBLISHED",
    "dateUpdated": "2024-08-02T14:14:40.034Z",
    "dateReserved": "2023-04-07T00:00:00",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "datePublished": "2023-07-06T00:00:00",
    "assignerShortName": "mitre"
  },
  "dataVersion": "5.1"
}