{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/socketio/socket.io/security/advisories/GHSA-25hc-qcg6-38wj",
            "name": "https://github.com/socketio/socket.io/security/advisories/GHSA-25hc-qcg6-38wj",
            "tags": [
              "x_refsource_CONFIRM",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/socketio/socket.io/commit/15af22fc22bc6030fcead322c106f07640336115",
            "name": "https://github.com/socketio/socket.io/commit/15af22fc22bc6030fcead322c106f07640336115",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/socketio/socket.io/commit/d30630ba10562bf987f4d2b42440fc41a828119c",
            "name": "https://github.com/socketio/socket.io/commit/d30630ba10562bf987f4d2b42440fc41a828119c",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          },
          {
            "url": "https://www.vicarius.io/vsociety/posts/unhandled-exception-in-socketio-cve-2024-38355"
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-19T07:47:44.453Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-38355",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-09-03T15:54:14.198687Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:socket:socket.io:*:*:*:*:*:node.js:*:*"
            ],
            "vendor": "socket",
            "product": "socket.io",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "lessThan": "2.5.1",
                "versionType": "custom"
              },
              {
                "status": "affected",
                "version": "3.0.0",
                "lessThan": "4.6.2",
                "versionType": "custom"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-09-03T20:35:24.356Z"
        }
      }
    ],
    "cna": {
      "title": "Unhandled 'error' event in socket.io",
      "source": {
        "advisory": "GHSA-25hc-qcg6-38wj",
        "discovery": "UNKNOWN"
      },
      "metrics": [
        {
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 7.3,
            "attackVector": "NETWORK",
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "integrityImpact": "LOW",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "LOW",
            "privilegesRequired": "NONE",
            "confidentialityImpact": "LOW"
          }
        }
      ],
      "affected": [
        {
          "vendor": "socketio",
          "product": "socket.io",
          "versions": [
            {
              "status": "affected",
              "version": "< 2.5.1"
            },
            {
              "status": "affected",
              "version": ">= 3.0.0,< 4.6.2"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://github.com/socketio/socket.io/security/advisories/GHSA-25hc-qcg6-38wj",
          "name": "https://github.com/socketio/socket.io/security/advisories/GHSA-25hc-qcg6-38wj",
          "tags": [
            "x_refsource_CONFIRM"
          ]
        },
        {
          "url": "https://github.com/socketio/socket.io/commit/15af22fc22bc6030fcead322c106f07640336115",
          "name": "https://github.com/socketio/socket.io/commit/15af22fc22bc6030fcead322c106f07640336115",
          "tags": [
            "x_refsource_MISC"
          ]
        },
        {
          "url": "https://github.com/socketio/socket.io/commit/d30630ba10562bf987f4d2b42440fc41a828119c",
          "name": "https://github.com/socketio/socket.io/commit/d30630ba10562bf987f4d2b42440fc41a828119c",
          "tags": [
            "x_refsource_MISC"
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "Socket.IO is an open source, real-time, bidirectional, event-based, communication framework. A specially crafted Socket.IO packet can trigger an uncaught exception on the Socket.IO server, thus killing the Node.js process. This issue is fixed by commit `15af22fc22` which has been included in `socket.io@4.6.2` (released in May 2023). The fix was backported in the 2.x branch as well with commit `d30630ba10`. Users are advised to upgrade. Users unable to upgrade may attach a listener for the \"error\" event to catch these errors.\n"
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-20",
              "description": "CWE-20: Improper Input Validation"
            }
          ]
        },
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-754",
              "description": "CWE-754: Improper Check for Unusual or Exceptional Conditions"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2024-06-19T19:48:50.193Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-38355",
    "state": "PUBLISHED",
    "dateUpdated": "2024-09-03T20:35:40.515Z",
    "dateReserved": "2024-06-14T14:16:16.464Z",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "datePublished": "2024-06-19T19:48:50.193Z",
    "assignerShortName": "GitHub_M"
  },
  "dataVersion": "5.1"
}