{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/JamesNK/Newtonsoft.Json/issues/2457",
            "tags": [
              "issue-tracking",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/JamesNK/Newtonsoft.Json/pull/2462",
            "tags": [
              "related",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/JamesNK/Newtonsoft.Json/commit/7e77bbe1beccceac4fc7b174b53abfefac278b66",
            "tags": [
              "related",
              "x_transferred"
            ]
          },
          {
            "url": "https://alephsecurity.com/2018/10/22/StackOverflowException/",
            "tags": [
              "related",
              "x_transferred"
            ]
          },
          {
            "url": "https://alephsecurity.com/vulns/aleph-2018004",
            "tags": [
              "related",
              "x_transferred"
            ]
          },
          {
            "url": "https://security.snyk.io/vuln/SNYK-DOTNET-NEWTONSOFTJSON-2774678",
            "tags": [
              "related",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/advisories/GHSA-5crp-9r3c-p9vr",
            "tags": [
              "third-party-advisory",
              "x_transferred"
            ]
          },
          {
            "url": "https://vulncheck.com/advisories/vc-advisory-GHSA-5crp-9r3c-p9vr",
            "tags": [
              "third-party-advisory",
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-01T22:35:33.415Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 7.5,
              "attackVector": "NETWORK",
              "baseSeverity": "HIGH",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "integrityImpact": "NONE",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "NONE"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-21907",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-03-21T19:31:50.211590Z"
              }
            }
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-09-06T14:53:56.776Z"
        }
      }
    ],
    "cna": {
      "title": "Improper Handling of Exceptional Conditions in Newtonsoft.Json",
      "source": {
        "discovery": "INTERNAL"
      },
      "affected": [
        {
          "versions": [
            {
              "status": "affected",
              "version": "0",
              "lessThan": "13.0.1",
              "versionType": "semver 2.0.0"
            }
          ],
          "packageName": "Newtonsoft.Json",
          "collectionURL": "https://nuget.org/packages",
          "defaultStatus": "unaffected"
        }
      ],
      "references": [
        {
          "url": "https://github.com/JamesNK/Newtonsoft.Json/issues/2457",
          "tags": [
            "issue-tracking"
          ]
        },
        {
          "url": "https://github.com/JamesNK/Newtonsoft.Json/pull/2462",
          "tags": [
            "related"
          ]
        },
        {
          "url": "https://github.com/JamesNK/Newtonsoft.Json/commit/7e77bbe1beccceac4fc7b174b53abfefac278b66",
          "tags": [
            "related"
          ]
        },
        {
          "url": "https://alephsecurity.com/2018/10/22/StackOverflowException/",
          "tags": [
            "related"
          ]
        },
        {
          "url": "https://alephsecurity.com/vulns/aleph-2018004",
          "tags": [
            "related"
          ]
        },
        {
          "url": "https://security.snyk.io/vuln/SNYK-DOTNET-NEWTONSOFTJSON-2774678",
          "tags": [
            "related"
          ]
        },
        {
          "url": "https://github.com/advisories/GHSA-5crp-9r3c-p9vr",
          "tags": [
            "third-party-advisory"
          ]
        },
        {
          "url": "https://vulncheck.com/advisories/vc-advisory-GHSA-5crp-9r3c-p9vr",
          "tags": [
            "third-party-advisory"
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "Newtonsoft.Json before version 13.0.1 is affected by a mishandling of exceptional conditions vulnerability. Crafted data that is passed to the JsonConvert.DeserializeObject method may trigger a StackOverflow exception resulting in denial of service. Depending on the usage of the library, an unauthenticated and remote attacker may be able to cause the denial of service condition.\n",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "Newtonsoft.Json before version 13.0.1 is affected by a mishandling of exceptional conditions vulnerability. Crafted data that is passed to the JsonConvert.DeserializeObject method may trigger a StackOverflow exception resulting in denial of service. Depending on the usage of the library, an unauthenticated and remote attacker may be able to cause the denial of service condition.<br>",
              "base64": false
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-755",
              "description": "CWE-755 Improper Handling of Exceptional Conditions"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "83251b91-4cc7-4094-a5c7-464a1b83ea10",
        "shortName": "VulnCheck",
        "dateUpdated": "2024-01-03T15:23:04.441Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-21907",
    "state": "PUBLISHED",
    "dateUpdated": "2024-09-06T18:26:37.445Z",
    "dateReserved": "2024-01-03T14:21:17.582Z",
    "assignerOrgId": "83251b91-4cc7-4094-a5c7-464a1b83ea10",
    "datePublished": "2024-01-03T15:23:04.441Z",
    "assignerShortName": "VulnCheck"
  },
  "dataVersion": "5.1"
}